export const GET_ACCOUNT_LIST = 'GET_ACCOUNT_LIST';
export const GET_ACCOUNT_DETAIL = 'GET_ACCOUNT_DETAIL';

export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_SETTING = 'GET_USER_SETTING';
export const GET_USER_DETAIL = 'GET_USER_DETAIL';
